name: Ansible Lint
description: Run Ansible Lint
author: Ansible by Red Hat <info@ansible.com>
branding:
  icon: shield
  color: red
inputs:
  path:
    description: >
      Specific path to lint instead of the default `.`. Multiple arguments are
      not supported and you will need to alter linter configuration to
      accommodate other use cases.
    required: false
    default: "."
  args:
    description: deprecated
    deprecationMessage: >
      Arbitrary args are no longer accepted, please use path instead and
      linter own configuration file to change its behavior.
    required: false
    default: ""
runs:
  using: docker
  image: docker://quay.io/ansible/creator-ee:v0.4.1
  entrypoint: /usr/local/bin/ansible-lint
  env:
    # These tell ansible-lint to use github compatible annotation format:
    GITHUB_ACTIONS: "true"
    GITHUB_WORKFLOW: "{{ github.workflow.name }}"
  args:
    - -vvv
    - ${{ inputs.path }}
